#!/usr/bin/env bash

sink=`pactl list sinks short | grep analog-stereo | awk '{print $1}'`

volume() {
    pactl list sinks \
    | grep '^[[:space:]]Volume:' \
    | head -n $(( $sink + 1 )) \
    | tail -n 1 \
    | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,'
}

render() {
    if [[ -z "$1" ]]; then
        echo "`volume`%"
    elif (( `volume` >= 100 )) && [[ "$1" == "+5%" ]]; then
        echo "`volume`%"
    else
        pactl set-sink-volume $sink "$1"
        echo "`volume`%"
    fi
}


case $BLOCK_BUTTON in
    1) pavucontrol  ;;
    2) render "0%"  ;;
    4) render "+5%" ;;
    5) render "-5%" ;;
    *) render       ;;
esac
