#!/usr/bin/env bash

status=`cmus-remote -Q | grep status`
status=${status#status }
artist=`cmus-remote -Q | grep 'tag artist'`
artist=${artist#tag artist }
title=`cmus-remote -Q | grep 'tag title'`
title=${title#tag title }

if [[ -z $title ]] && [[ -z $artist ]]; then
  file=`cmus-remote -Q | grep 'file'`
  file=${file#file }
fi

if [[ $status == "stopped" ]]; then
  echo "Stopped"
elif [[ $status == "paused" ]]; then
  echo "Paused"
elif [[ $status == "playing" ]]; then
  if [[ -n $file ]]; then
    echo $file
  elif [[ -z $artist ]]; then
    echo "Unknown - $title"
  elif [[ -z $title ]]; then
    echo "$artist - Untitled"
  else
    echo "$artist - $title"
  fi
else
  exit 0
fi

case $BLOCK_BUTTON in
  1) cmus-remote --prev  ;;
  2) cmus-remote --pause ;;
  3) cmus-remote --next  ;;
esac

